### ISSUE TITLE
BUG: v0.11.0 of widgets break

### ISSUE THREAD

**Issue by liquidiert** [alex-gutev/live_cells#4]
Current version of widgets break with this exception:
![image](https://github.com/user-attachments/assets/c83bd67d-2b58-4a7d-a7ef-e4edf0e27f1d)
I think it has to do with supporting Flutter 3.24.0?

**Comment by alex-gutev** [comment]
I rebuilt the widgets library and tested everything with Flutter 3.24.3 to make sure everything still works. I guess now the widget library is incompatible with earlier Flutter versions. This only affects the `live_cell_widgets` library and not `live_cells`, that is it affects the Cell variants of the widgets but not `CellWidget`.

I think a solution is possible using conditional exports, to export different versions of the widgets library based on the Flutter version. Until it's ready you may be able to use the earlier version, 0.10.1, of `live_cell_widgets` by putting it in `dependency_overrides`. There are no changes to the widget library other than supporting Flutter 3.24.3

**Comment by liquidiert** [comment]
Thanks that explains it!
