### ISSUE TITLE
QUESTION: wait cells

### ISSUE THREAD

**Issue by liquidiert** [alex-gutev/live_cells#6]
Hey! I Have a question about wait cells. I have the following code:
```dart
late final ValueCell<Future<List<Client>>> _clientsFuture =
    ValueCell.computed(
  () async {
    final clientsResp = await ClientService().get(
      context,
    );
    if (clientsResp is PCCSuccess<List<Client>>) {
      return clientsResp.data;
    } else {
      throw clientsResp as PCCError;
    }
  },
);

late final _clients = _clientsFuture.wait.onError(<Client>[].cell);
```
Now the _clients cell only gets evaluated once with the onError value. Once the _clientsFuture was computed it does save its value in _clients. I guess because the onError fallback does not allow for automatic re-evaluation? Or maybe it has to do with me using it in a stateless widget and late 😓 
Is there a way to retrigger the _clientsFuture other than this:
```dart
final triggerCell = ValueCell<int>(0);

late final ValueCell<Future<List<Client>>> _clientsFuture = ValueCell.computed(
  () async {
    // Access triggerCell.value to depend on it
    triggerCell.value;

    final clientsResp = await ClientService().get(context);
    if (clientsResp is PCCSuccess<List<Client>>) {
      return clientsResp.data;
    } else {
      throw clientsResp as PCCError;
    }
  },
);

late final _clients = _clientsFuture.wait.onError(<Client>[].cell);

void refreshClients() {
  // Increment triggerCell to trigger recomputation
  triggerCell.value++;
}
```

**Comment by liquidiert** [comment]
Ah I found [this[(https://livecell.gutev.dev/docs/basics/action-cells#triggering-actions) in the docs but I think it would be nicer if wait cells woudl re-evaluate automatically.

**Comment by alex-gutev** [comment]
The `_clients` cell should reevaluate itself automatically whenever the state of the `Future` held in `_clientsFuture` changes, that is when the `Future` completes with a value or an error.

Action cells, which you linked to, are used to cause `_clientsFuture` to refresh it's value. This is useful for refreshing the data that is shown on the screen, as part of a pull to refresh gesture for example, or for retrying a failed network request.

**Comment by liquidiert** [comment]
Thank you for the explanation. I'll go ahead and close this :)

**Comment by alex-gutev** [comment]
Just to add, you shouldn't use `.value` inside `ValueCell.computed` or `ValueCell.watch` since it doesn't do dependency tracking. You should use the function call syntax e.g. `triggerCell()` instead.
